const details = {
  detail: {
// general
    roadLegal: false,
    engine: '2-stroke',
    licenseType: 'NA',
    capacity: 125,
    minRentalPeriod: 1,
    maxPower: 35,
    weight: 120,
    topSpeed: 110,
    seatHeight: 992,
    torque: 28,
    maxRiders: 1,
    acceleration: 5,

    cylinderCount: 1,
    bore: 55,
    stroke: 65,
    transmission: '6 gears, MT',
    compressionRatio: 'xxx',
    suspension: 'Sanchez',
    frame: 'Alloy',
    wheelbase: 1597,
    rakeTrail: 'wtf',
    wheelSizes: '21" F, 19" R',
    tires: 'Excel',
    brakes: 'Brembo',
    fuelCapacity: 7.5,
    ignitionType: 'Kickstarr',
    kickstand: false,
    lights: 'none',
    storageSpace: false,
    generalState: 'Very Good',
    motoHours: 25,
    riderExperience: 'Begginer',
    minimumDriverAge: 16,
    maintenanceRequired: 'There is a broken right handle, but it is ok to drive anyway',
    maintenanceHistory: 'New air filters and brake pads',
  },
  other: {
    helmet: {
      make: 'HJC Helmets',
      model: 'RPHA MAX Evo',
      certificates: 'Pinlock',
      age: 2017,
      state: 'New',
      type: 'Full Protection',
      picture: 'url-to-helmet-picture',
    },
    gloves: true,
    boots: true,
    jacket: true,
    vest: true,
    chestProtector: true,
    buzzer: true,
    pants: true,
    knees: true,
    elbows: true,
    goggles: true,
    neckBrace: true,
    travelBoxes: true,
    lock: true,
    camera: true,
    basicTools: 'included',
    firstAidKit: true,
    parkingGarage: false,
    recommendedMechanic: false,
    transportTheMorocycle: false,
    transportToFromMotorcycle: false,
    photographer: false,
    mechanicalChangesOptions: false,
    guide: false,
    coach: false,
    group: false,
    club: false,
    nearbyCircuitTrail: false,
  },
};

const offer = {
  ...details,
  title: 'KTM SX 125, 2012',
  type: 'motocross',
  instance: 3,
  description: 'Those wanting to race in the Junior World Championship need look no further than the 125 SX. The free-revving and lively two-stroke engine has gained even more performance for the current season.',
  images: {
    main: 'http://p.vitalmx.com/photos/users/64/photos/83572/s1600_125_SX_90Grad.jpg',
  },
  offerer: {
    id: 1,
    picture: 'https://scontent-waw1-1.cdninstagram.com/t51.2885-15/e35/15877344_344661349253204_5404343355553349632_n.jpg',
    fullname: 'Michal Mikolajczyk',
    since: '31 Dec 1986',
    location: {
      city: 'Warsaw',
      country: 'Poland',
    },
    descript: 'My name is Mike and I like to ride motocross… but I will ride any bike, really. Ask me for local tracks and instructors – my friends and I ride and race every week. Our garage is in Warsaw Powisle.',
    recommend: 9,
  },
  price: {
    hour: 20,
    day: 55,
    part: 100,
  },
}

export {
  offer
};
